baseURL = "https://antonioalmeida.github.io"
languageCode = "en-us"
title = "António Almeida"
theme = "tex"
copyright = "&copy; António Almeida</a> 2024"

[params]
    nickname = "antonioalmeida"
    name = "António Almeida"
    bio = ["Software Engineer", "Handball Player", "Enumerator of things"]

[[params.social]]
  name = "Github"
  url = "https://github.com/antonioalmeida"

[[params.social]]
  name = "Bluesky"
  url = "https://bsky.app/profile/xu.pt"

[[params.social]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/theantonioalmeida"

[[params.social]]
  name = "CV"
  url = "/cv.pdf"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4